# 💰 Configuration du plugin MoneyFromOres

# 🎲 Chance d'obtenir une récompense lors de la casse d'un minerai (0.0 à 1.0)
chance: 0.3 # 30% de chance. 1.0 = 100%, 0.0 = jamais

# 🔧 Récompenses associées à chaque minerai
rewards:
  DIAMOND_ORE: 20.0
  DEEPSLATE_DIAMOND_ORE: 22.0
  EMERALD_ORE: 18.0
  DEEPSLATE_EMERALD_ORE: 20.0
  GOLD_ORE: 15.0
  DEEPSLATE_GOLD_ORE: 16.5
  IRON_ORE: 10.0
  DEEPSLATE_IRON_ORE: 11.0
  COPPER_ORE: 8.0
  DEEPSLATE_COPPER_ORE: 8.5
  REDSTONE_ORE: 6.0
  DEEPSLATE_REDSTONE_ORE: 6.5
  LAPIS_ORE: 7.0
  DEEPSLATE_LAPIS_ORE: 7.5
  NETHER_QUARTZ_ORE: 5.0
  NETHER_GOLD_ORE: 4.5

# 💬 Messages affichés au joueur
messages:
  reward: "§aTu as gagné {amount} money pour avoir miné un {ore} ! (x{multiplier})"
  anti_farm: "§cPas de récompense : ce minerai a été placé manuellement."
  no_reward: "§7Ce minerai ne donne pas de récompense."

# ✨ Effets visuels et sonores (désactive avec 'none' ou 'enabled: false')
effects:
  enabled: true
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  particle: VILLAGER_HAPPY
