rewards:
  DIAMOND_ORE: 20.0
  GOLD_ORE: 15.0
  IRON_ORE: 10.0
  EMERALD_ORE: 25.0
  COPPER_ORE: 8.0
  REDSTONE_ORE: 5.0
  LAPIS_ORE: 5.0

messages:
  reward: "§aTu viens de gagner {amount} money pour avoir miné un {ore} !"
